# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    cocoapods( clean_install: true )
    # tests
    install_provisioning_profile(path: "./profiles/Profile_Prod_MJ_Agente_de_Campo.mobileprovision")
    build_app(workspace: "SinespAgenteCampo.xcworkspace", scheme: "SinespAgenteCampo")
    changelog = File.read("../Changelog.txt")
    upload_to_testflight(changelog: changelog, skip_waiting_for_build_processing: true)
    version = get_version_number(xcodeproj: "SinespAgenteCampo.xcodeproj", target: "SinespAgenteCampo")
    build = get_build_number(xcodeproj: "SinespAgenteCampo.xcodeproj").to_i
    git_commit(path: ".", message: "Update version #{version}.#{build}")
    build = build + 1
    increment_build_number( build_number: build, xcodeproj: "SinespAgenteCampo.xcodeproj")
  end
  lane :tests do
      run_tests(workspace: "SinespAgenteCampo.xcworkspace", scheme: "SinespAgenteCampo", devices: ["iPhone 8"])
  end
end
